// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'bun run generate-models' to update

import values from "./data/amazon-bedrock.json" with { type: "json" };
import { flattenModelCatalogFromUnknown } from "../model-catalog.ts";

export const AMAZON_BEDROCK_MODELS =
	flattenModelCatalogFromUnknown("amazon-bedrock", values) as any;
