// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'bun run generate-models' to update

import values from "./data/ant-ling.json" with { type: "json" };
import { flattenModelCatalogFromUnknown } from "../model-catalog.ts";

export const ANT_LING_MODELS =
	flattenModelCatalogFromUnknown("ant-ling", values) as any;
