// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'bun run generate-models' to update

import values from "./data/cloudflare-ai-gateway.json" with { type: "json" };
import { flattenModelCatalogFromUnknown } from "../model-catalog.ts";

export const CLOUDFLARE_AI_GATEWAY_MODELS =
	flattenModelCatalogFromUnknown("cloudflare-ai-gateway", values) as any;
