// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/cloudflare-workers-ai.json" with { type: "json" };
import { flattenModelCatalogFromUnknown } from "../model-catalog.ts";

export const CLOUDFLARE_WORKERS_AI_MODELS =
	flattenModelCatalogFromUnknown("cloudflare-workers-ai", values) as any;
