// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'bun run generate-models' to update

import values from "./data/deepseek.json" with { type: "json" };
import { flattenModelCatalogFromUnknown } from "../model-catalog.ts";

export const DEEPSEEK_MODELS =
	flattenModelCatalogFromUnknown("deepseek", values) as any;
