// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'bun run generate-models' to update

import values from "./data/github-copilot.json" with { type: "json" };
import { flattenModelCatalogFromUnknown } from "../model-catalog.ts";

export const GITHUB_COPILOT_MODELS =
	flattenModelCatalogFromUnknown("github-copilot", values) as any;
