// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'bun run generate-models' to update

import values from "./data/huggingface.json" with { type: "json" };
import { flattenModelCatalogFromUnknown } from "../model-catalog.ts";

export const HUGGINGFACE_MODELS =
	flattenModelCatalogFromUnknown("huggingface", values) as any;
