// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'bun run generate-models' to update

import values from "./data/kimi-coding.json" with { type: "json" };
import { flattenModelCatalogFromUnknown } from "../model-catalog.ts";

export const KIMI_CODING_MODELS =
	flattenModelCatalogFromUnknown("kimi-coding", values) as any;
