// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'bun run generate-models' to update

import values from "./data/moonshotai-cn.json" with { type: "json" };
import { flattenModelCatalogFromUnknown } from "../model-catalog.ts";

export const MOONSHOTAI_CN_MODELS =
	flattenModelCatalogFromUnknown("moonshotai-cn", values) as any;
