// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'bun run generate-models' to update

import values from "./data/opencode-go.json" with { type: "json" };
import { flattenModelCatalogFromUnknown } from "../model-catalog.ts";

export const OPENCODE_GO_MODELS =
	flattenModelCatalogFromUnknown("opencode-go", values) as any;
