// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/qwen-token-plan-individual.json" with { type: "json" };
import { flattenModelCatalogFromUnknown } from "../model-catalog.ts";

export const QWEN_TOKEN_PLAN_INDIVIDUAL_MODELS =
	flattenModelCatalogFromUnknown("qwen-token-plan-individual", values) as any;
