// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/vercel-ai-gateway.json" with { type: "json" };
import { flattenModelCatalogFromUnknown } from "../model-catalog.ts";

export const VERCEL_AI_GATEWAY_MODELS =
	flattenModelCatalogFromUnknown("vercel-ai-gateway", values) as any;
