// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'bun run generate-models' to update

import values from "./data/xiaomi.json" with { type: "json" };
import { flattenModelCatalogFromUnknown } from "../model-catalog.ts";

export const XIAOMI_MODELS =
	flattenModelCatalogFromUnknown("xiaomi", values) as any;
