// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'bun run generate-models' to update

import values from "./data/xiaomi-token-plan-sgp.json" with { type: "json" };
import { flattenModelCatalogFromUnknown } from "../model-catalog.ts";

export const XIAOMI_TOKEN_PLAN_SGP_MODELS =
	flattenModelCatalogFromUnknown("xiaomi-token-plan-sgp", values) as any;
