// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'bun run generate-models' to update

import values from "./data/zai-coding-cn.json" with { type: "json" };
import { flattenModelCatalogFromUnknown } from "../model-catalog.ts";

export const ZAI_CODING_CN_MODELS =
	flattenModelCatalogFromUnknown("zai-coding-cn", values) as any;
